新增诸多资源
Xovee/uestc-course pull request #96
Opened 2024-01-18 11:12 UTC by jjq419875574

1. 更改“操作系统基础”课程名为“操作系统原理及实践”，该课程为信软课程，最新课程名为“操作系统原理及实践”，此前叫做“操作系统基础”。保持课程名称和最新一致。
2. 更新“计算机系统结构”相关课程资源（真题+复习资料）
3. 更新“概率论”复习资料相关资料
4. 更新“大学物理”相关资料，主要是信软单独的考试题。（大物信软学院考试内容和其他学院不同）
5. 新增“离散数学”课程
6. 新增“金融学基础”课程
7. 更新“程序设计与算法基础”课程相关资源（主要是网上的资源，已经经过验证是真实地真题）
8. 更新“金融衍生工具”相关资源（主要是网上的资源和自己的笔记等）
9. 更新“马克思主义基本原理”和“毛泽东思想与中国特色社会主义理论体系概论”真题等

2024-01-18 11:31 UTC, Xovee commented
感谢资源贡献，检查后会合并到主仓库，你也可以在贡献者名单中添加自己的昵称和留言

2024-01-27 06:54 UTC, Xovee requested changes
请修改标记为【需要修正】的项目，谢谢！

- 大学物理作业PDF打不开【需要修正】
- 操作系统试卷PDF打不开【需要修正】
- 操作系统复习资料：复习提纲v4.ppt, v4改.ppt, 操作系统期末复习练习题（含答案）.ppt 打不开【需要修正】
- 金融学基础2022秋作业及答案-赵洪江老师.pdf 打不开【需要修正】

2024-01-27 06:54 UTC, Xovee commented on 课程目录/金融学基础/作业/金融学基础2022秋作业及答案-赵洪江老师.pdf
文件打不开

2024-01-27 12:05 UTC, jjq419875574 commented
所有需要修正的部分均已经重新上传修改，大概率可能是我上传的时候代理掉线了没传成功😂
烦请重新审查🌞

2024-01-27 12:40 UTC, Xovee approved these changes
great

2024-01-27 12:41 UTC, merged

2024-01-27 12:50 UTC, Xovee commented
资源已全部合并到主仓库！
感谢贡献这么多资源～祝期末门门100～ 🥳